#-- Lattice Semiconductor Corporation Ltd.
#-- Map run script generated by Radiant

set ret 0
if {[catch {

sys_set_attribute -gui on -msg {C:/Users/javos/workspace/DualCore/promote.xml}
msg_load {C:/Users/javos/workspace/DualCore/promote.xml}
des_set_project_udb -in {DualCore_impl_1_syn.udb} -out {DualCore_impl_1_map.udb} -milestone map -pm jd5s00
map_set_option {pdc_file "C:/Users/javos/workspace/DualCore/source/impl_1/DualCore.pdc"}
# map option
map_set_option { report_symbol_cross_reference false report_signal_cross_reference false infer_gsr false  ignore_constraint_errors false}
map_run

} out]} {
   runtime_log $out
   set ret 1
}
exit -force ${ret}
