// >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
// ------------------------------------------------------------------
// Copyright (c) 2019-2023 by Lattice Semiconductor Corporation
// ALL RIGHTS RESERVED
// ------------------------------------------------------------------
//
// IMPORTANT: THIS FILE IS USED BY OR GENERATED BY the LATTICE PROPEL
// DEVELOPMENT SUITE, WHICH INCLUDES PROPEL BUILDER AND PROPEL SDK.
//
// Lattice grants permission to use this code pursuant to the
// terms of the Lattice Propel License Agreement.
//
// DISCLAIMER:
//
//  LATTICE MAKES NO WARRANTIES ON THIS FILE OR ITS CONTENTS, WHETHER
//  EXPRESSED, IMPLIED, STATUTORY, OR IN ANY PROVISION OF THE LATTICE
//  PROPEL LICENSE AGREEMENT OR COMMUNICATION WITH LICENSEE, AND LATTICE 
//  SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTY OF MERCHANTABILITY OR
//  FITNESS FOR A PARTICULAR PURPOSE.  LATTICE DOES NOT WARRANT THAT THE
//  FUNCTIONS CONTAINED HEREIN WILL MEET LICENSEE'S REQUIREMENTS, OR THAT
//  LICENSEE'S OPERATION OF ANY DEVICE, SOFTWARE OR SYSTEM USING THIS FILE
//  OR ITS CONTENTS WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT DEFECTS
//  HEREIN WILL BE CORRECTED.  LICENSEE ASSUMES RESPONSIBILITY FOR 
//  SELECTION OF MATERIALS TO ACHIEVE ITS INTENDED RESULTS, AND FOR THE
//  PROPER INSTALLATION, USE, AND RESULTS OBTAINED THEREFROM.  LICENSEE
//  ASSUMES THE ENTIRE RISK OF THE FILE AND ITS CONTENTS PROVING DEFECTIVE
//  OR FAILING TO PERFORM PROPERLY AND IN SUCH EVENT, LICENSEE SHALL 
//  ASSUME THE ENTIRE COST AND RISK OF ANY REPAIR, SERVICE, CORRECTION, OR
//  ANY OTHER LIABILITIES OR DAMAGES CAUSED BY OR ASSOCIATED WITH THE 
//  SOFTWARE.  IN NO EVENT SHALL LATTICE BE LIABLE TO ANY PARTY FOR DIRECT,
//  INDIRECT,SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST
//  PROFITS, ARISING OUT OF THE USE OF THIS FILE OR ITS CONTENTS, EVEN IF
//  LATTICE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. LATTICE'S
//  SOLE LIABILITY, AND LICENSEE'S SOLE REMEDY, IS SET FORTH ABOVE.  
//  LATTICE DOES NOT WARRANT OR REPRESENT THAT THIS FILE, ITS CONTENTS OR
//  USE THEREOF DOES NOT INFRINGE ON THIRD PARTIES' INTELLECTUAL PROPERTY
//  RIGHTS, INCLUDING ANY PATENT. IT IS THE USER'S RESPONSIBILITY TO VERIFY
//  THE USER SOFTWARE DESIGN FOR CONSISTENCY AND FUNCTIONALITY THROUGH THE
//  USE OF FORMAL SOFTWARE VALIDATION METHODS.
// ------------------------------------------------------------------



// CPU0


#include "gpio.h"
#include "hal.h"
#include "utils.h"
#include <stdio.h>
#include "sys_platform.h"

#if (defined LSCC_STDIO_UART_APB) && (defined UART_INST_BASE_ADDR)
#include "uart.h"

struct uart_instance uart_core_uart;
#endif
#ifndef _UART_NO_INTERRUPTS_
#include "pic.h"
#endif

struct gpio_instance gpio_inst;

// global pointers and Definitions for to DualPort use CPU0
#define DP_EMPTY		0	// Flag indicating buffer is empty (read and not yey re written
#define CPU_BUSY		1	// DP Cpu status indicates busy, no time to read or write DP
#define CPU_READY		0	// DP Cpu status indicates ready, polling and handling DP
#define DP_SIZE 		64

uint8_t *DPcpu0_status = (uint8_t*) DUALPORT_INST_BASE_ADDR;    	// status register THIS cpu  = cpu0. read/write
uint8_t *DPcpu1_status = (uint8_t*) (DUALPORT_INST_BASE_ADDR +1); 	// status register OTHER cpu = cpu1. read only

uint8_t *DPwrite_size = (uint8_t*) (DUALPORT_INST_BASE_ADDR+2);    		// flag cpu0 indicates data bytes in write buffer
uint8_t *DPread_size = (uint8_t*) (DUALPORT_INST_BASE_ADDR +3); 		// flag cpu1 indicates data bytes in read buffer
uint8_t *DPwrite_buffer = (uint8_t*) (DUALPORT_INST_BASE_ADDR+4);  		// 128 bytes  buffercpu0 : write
uint8_t *DPread_buffer  = (uint8_t*) (DUALPORT_INST_BASE_ADDR+5+DP_SIZE);// 128 bytes buffer cpu1 : read only

uint8_t Gcounter=0;

static int lscc_uart_putc(char c, FILE *file)
{
#ifdef LSCC_STDIO_UART_APB
		int ret = EOF;
		ret = uart_putc(&uart_core_uart, c);
		if (c == '\n' && ret == 0)
			ret = uart_putc(&uart_core_uart, '\r');
		return ret;
#else
		return EOF;
#endif
}


static int lscc_uart_getc(FILE *file)
{
	(void) file;
	return EOF;
}


static int lscc_uart_flush(FILE *file)
{
	(void) file;
	return 0;
}


static void bsp_init(void)
{
	//initialize GPIO
	gpio_inst.instance_name = GPIO_INST_NAME;
	gpio_init(&gpio_inst, GPIO_INST_BASE_ADDR, GPIO_INST_LINES_NUM, GPIO_INST_GPIO_DIRS);

#if (defined LSCC_STDIO_UART_APB) && (defined UART_INST_BASE_ADDR)
#ifndef _UART_NO_INTERRUPTS_
	//setup uart IRQ
	pic_init(CPU0_INST_PICTIMER_START_ADDR);
	uart_core_uart.intrLevel = UART0_INST_IRQ;
	uart_core_uart.intrAvail = true;
	//pic_isr_register(UART0_INST_IRQ, uart_isr, (void *)&uart_core_uart);
#endif

	//initialize UART
	uart_init(&uart_core_uart, UART_INST_BASE_ADDR, UART_INST_SYS_CLK * 1000000, UART_INST_BAUD_RATE, 1, 8);
	iob_init(lscc_uart_putc, lscc_uart_getc, lscc_uart_flush);
#endif
	 //init DP Interface
	*DPwrite_size = DP_EMPTY;
	*DPcpu0_status = CPU_READY;
	delay(400); // wait for CPU1 to write status flags ?
}



uint8_t DPSend_request()
{
 uint16_t t,s=0;
 char c;
 if (*DPcpu1_status == CPU_READY)	 // check if cpu is available
	 if( *DPwrite_size == DP_EMPTY ) // check if last request was read
	 	 {
		 printf("\nCpu0 request send, data [");
		 Gcounter++;
		 s = DP_SIZE;
		 for(t=0;t<s;t++) // create data string of characters
		 	 {
			  c= 32+(Gcounter+t)%94; 	// ascii character #32 - #126 = 94
			  *(DPwrite_buffer+t) = (uint8_t) c; 	// write char to DPram
			  printf("%c",c);
		 	 }
		 *DPwrite_size = s; // flag the data size that is ready
		 printf("]\n");
	 	 }
 return(s);
}

uint8_t DPPoll_feedback()
{
uint16_t t,s=0;
char c;
if (*DPcpu1_status == CPU_READY)	 // check if cpu is available
	if( *DPread_size != DP_EMPTY ) // check if there is data to read
		 	 {
			 printf("Cpu1 sends data [");
		 	 s= *DPread_size;
		 	 if(s <= DP_SIZE) // check valid size
		 	 	 {
		 		 for(t=0;t<s;t++)
		 	 	 	{
		 			c = (char) *(DPread_buffer+t);
		 			printf("%c",c);
		 	 	 	}
		 	 	 }
			 else s=0;
	 		 *DPread_size=DP_EMPTY;
	 		 printf("]\n");
		 	 }
return(s);
}



int main(void) {
	static uint8_t idx = 0;
	static uint8_t pin_state = 0xFF;

	bsp_init();
    delay(1000);
	printf("\nRISCV DualCore Demo\n");

	while (true) {
		gpio_output_write(&gpio_inst, idx, pin_state);

		if (++idx == LED_COUNT) {
			idx = 0;
			pin_state = ~pin_state; // toggle leds
		}

		if (RTL_SIM) {
			delay(1);
		} else {
			delay(2000);
		}
		DPSend_request();
		DPPoll_feedback();
		printf("-");
	}

	return 0;
}

